//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class empresas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empresas()
        {
            this.vacantes_empresas = new HashSet<vacantes_empresas>();
        }
    
        public int ID { get; set; }
        public string nombre_empresa { get; set; }
        public string descricion { get; set; }
        public string modelo_negocio { get; set; }
        public Nullable<int> invercion { get; set; }
        public Nullable<int> porcentaje_participacion { get; set; }
        public int id_usuario { get; set; }
        public Nullable<int> Estado { get; set; }
    
        public virtual usuarios usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<vacantes_empresas> vacantes_empresas { get; set; }
    }
}
