//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class invercionista_socio
    {
        public int ID { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> porsentaje { get; set; }
        public Nullable<int> inversion { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> ID_proyecto { get; set; }
    
        public virtual proyectos proyectos { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
