//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Capa_entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class proyectos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public proyectos()
        {
            this.invercionista_socio = new HashSet<invercionista_socio>();
            this.ofertantes = new HashSet<ofertantes>();
        }
    
        public int ID { get; set; }
        public string NOMBRE_PROYECTO { get; set; }
        public string descripcion { get; set; }
        public string modelo_negocio { get; set; }
        public Nullable<int> invercion_necesaria { get; set; }
        public Nullable<int> porcentaje_ofertado { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string link_video { get; set; }
        public byte[] imagen { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<invercionista_socio> invercionista_socio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ofertantes> ofertantes { get; set; }
        public virtual usuarios usuarios { get; set; }
    }
}
